# hostname (and path) to the root
baseURL: "https://ryandejaegher.com"

# Caches
caches:
  getjson:
    maxAge: "5m"
    

# The language code for the site
languageCode: "en-us"

# Site title
title: "Ryan Dejaegher"

# theme to use (located by default in /themes/THEMENAME/)
theme: "my-theme"

# Permalinks
# See "content-management/permalinks"
permalinks:
  articles: /:title/
  notes: /:title/
  pages: /:title/
  developer-diary: /:title/

# Use absolute URLs
canonifyURLs: true

# Allows you to disable all page types and will render nothing related to 'kind';
# values = "page", "home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"
disableKinds: ["hugoGeneratorInject", "404"]

# Files to ignore while rendering
ignoreFiles: ['Template']

# the length of text to show in a .Summary
summaryLength: 5

# Pagination
paginate: 10
paginatePath: "/"

# Syntax Highlighting
pygmentsCodefences: true
pygmentsUseClasses: true

# Enable to get file modification date from Github
enableGitInfo: true

metaDataFormat: "yaml"

# Image Processing Options
imaging:
  quality: 80
  anchor: "smart"
  resampleFilter: "Gaussian"


# This outputs a hugo_stats.json file in the root which can be used with PostCSS and PostProcess to Purge CSS
build: 
  writeStats: true

# Output formats
outputs:
  section:
    - HTML
    - RSS
    - JSON
  page: 
    - HTML
    - RSS
    - AMP
    - JSON
  home: 
    - HTML
    - RSS
    - Algolia


outputFormats:
  Algolia:
    baseName: "algolia"
    isPlainText: true
    mediaType: "application/json"
    notAlternative: true


