---
baseURL: http://your-domain.com
title: Ryan Dejaegher

params:
  description: A starter repo for Hugo
  rssURL:
    main: https://gomakethings.com/feed/index.xml
  rssLimit: "7"


caches:
  getjson:
    maxAge: 5m
languageCode: en-us
theme: my-theme

permalinks:
  articles: "/:title/"
canonifyURLs: true

disableKinds:
- RSS
- hugoGeneratorInject
- '404'
ignoreFiles: []

summaryLength: "70"

# Pagination
paginate: "35"
paginatePath: page
blackfriday:
  fractions: false
pygmentsCodefences: true
pygmentsUseClasses: true
