# hostname (and path) to the root
baseURL: "http://your-domain.com"

# Caches
caches:
  getjson:
    maxAge: "5m"

menu:
  main:
  - url: https://apple.com
    name: Wow
    weight: 3

# The language code for the site
languageCode: "en-us"

# Site title
title: "My Hugo Site"

# theme to use (located by default in /themes/THEMENAME/)
theme: "my-theme"

# Permalinks
# See "content-management/permalinks"
permalinks:
  articles: /:title/

# Use absolute URLs
canonifyURLs: true

# Allows you to disable all page types and will render nothing related to 'kind';
# values = "page", "home", "section", "taxonomy", "taxonomyTerm", "RSS", "sitemap", "robotsTXT", "404"
disableKinds: ["RSS", "hugoGeneratorInject", "404"]

# Files to ignore while rendering
ignoreFiles: []

# the length of text to show in a .Summary
summaryLength: 70

# Pagination
paginate: 35
paginatePath: "page"


# Syntax Highlighting
pygmentsCodefences: true
pygmentsUseClasses: true