defaultMarkdownHandler: goldmark
goldmark:
  extensions:
    footnote: true
    typographer: true
  parser:
    attribute: true
    autoHeadingID: true
    autoHeadingIDType: github
  renderer:
    unsafe: true
tableOfContents:
  endLevel: 4
  ordered: false
  startLevel: 2