goldmark:
  extensions:
    definitionList: true
    footnote: true
    linkify: true
    strikethrough: true
    table: true
    taskList: true
    typographer: true
  parser:
    attribute: true
    autoHeadingID: true
    autoHeadingIDType: github
  renderer:
    hardWraps: false
    unsafe: false
    xhtml: false
highlight:
  codeFences: true
  guessSyntax: false
  hl_Lines: ""
  lineNoStart: 1
  lineNos: false
  lineNumbersInTable: true
  noClasses: true
  style: monokai
  tabWidth: 4
tableOfContents:
  endLevel: 3
  ordered: false
  startLevel: 2