---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content
  label: Content
  create: all
  match: "**/*"
- type: directory
  path: config/_default
  label: Config
  create: all
  match: "**/*"
- type: heading
  label: Content
- type: directory
  path: content/articles
  label: Articles
  create: all
  match: "**/*"
  templates:
  - article
  - list-page
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
  templates:
  - block-page
  - page
- type: directory
  path: content/products
  label: Products
  create: all
  match: "**/*"
  templates:
  - product
- type: directory
  path: content/rss-feed
  label: Rss feed
  create: all
  match: "**/*"
- type: heading
  label: Config
- type: heading
  label: Data
- type: directory
  path: data
  label: Data
  create: documents
  match: "**/*"
  new_doc_ext: yaml
upload_dir: assets/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.71.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.71.1
