---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: directory
  path: content/articles
  label: Articles
  create: all
  match: "**/*"
  templates:
  - block-page
  - article
  - list-page
- type: directory
  path: content/developer-diary
  label: Developer Diary
  create: all
  match: "**/*"
  templates:
  - article
- type: heading
  label: Data
- type: directory
  path: data
  label: Data
  create: documents
  match: "**/*"
  new_doc_ext: yaml
- type: directory
  path: config/_default
  label: Config
  create: all
  match: "**/*"
upload_dir: themes/my-theme/assets/uploads
public_path: "/uploads"
front_matter_path: "/uploads"
use_front_matter_path: true
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.80.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.71.1
